[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install -r artifacts/tg-python/requirements.txt"]

[start]
cmd = "cd artifacts/tg-python && python3 server.py"
